CREATE DATABASE IF NOT EXISTs Products_db;
CREATE TABLE IF NOT EXISTS Products_db.Products(
   id int PRIMARY KEY AUTO_INCREMENT,
   Product_name VARCHAR(100),
   Price decimal,
   Date_ DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
